<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Back to other options</name>
   <tag></tag>
   <elementGuidId>b04b5c63-841f-4186-bc3f-38d78d902650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phone-signin-back-other-options > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='phone-signin-back-other-options']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9cc7fc87-c47a-49a6-9f86-c21f2257f8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back to other options</value>
      <webElementGuid>cbf097e2-1747-4cef-840a-384944b51bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-signin-back-other-options&quot;)/span[1]</value>
      <webElementGuid>ee342ae0-d349-4bc7-8088-4f504af07eef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='phone-signin-back-other-options']/span</value>
      <webElementGuid>8db2d112-3291-4fdb-b1e8-f3b87281f053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send OTP'])[1]/following::span[1]</value>
      <webElementGuid>08be38e3-04d2-435a-a53a-2c4023917ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::span[2]</value>
      <webElementGuid>37a734ce-6fd9-4a90-af38-cedfcc9f4655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'phone-signin-back-other-options', '&quot;', ')/span[1]')])[1]/preceding::span[1]</value>
      <webElementGuid>acd27198-2268-4f4b-b25d-13ddf3ed101f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back to other options']/parent::*</value>
      <webElementGuid>0da04c92-51ae-4716-9116-928e0fc1b659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a/span</value>
      <webElementGuid>f0c55fad-1e93-46c2-890d-28c0230fbdbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Back to other options' or . = 'Back to other options')]</value>
      <webElementGuid>3e1cdbb6-11a2-4064-a3f3-498b18349caf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
