<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tenants</name>
   <tag></tag>
   <elementGuidId>b091b1dc-ff9f-47c5-92c4-2066408d563c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Landlords'])[2]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8d244235-4b4b-4ec6-9780-860c2292f4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tenants</value>
      <webElementGuid>0af43879-5359-4390-a86c-f45a0d86d02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-landing[1]/app-landing-header[1]/nav[@class=&quot;bg-bg-3 sticky-top py-4 py-lg-7&quot;]/div[@class=&quot;d-none d-lg-block&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center justify-content-between&quot;]/div[@class=&quot;text-center d-flex justify-content-center col-6&quot;]/a[@class=&quot;fw-bold mx-4 text-dark-1 aos-init aos-animate&quot;]/span[1]</value>
      <webElementGuid>2ed40746-e283-473f-ba97-f32fba387f6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Landlords'])[2]/following::span[1]</value>
      <webElementGuid>17331490-fc19-4ac0-85c1-f4099ede9b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/following::span[2]</value>
      <webElementGuid>f5b74892-5859-409b-a78b-94e181cc170b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[2]/preceding::span[1]</value>
      <webElementGuid>ac17ad64-6e96-4dd6-928d-bd5459c147fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[2]/preceding::span[2]</value>
      <webElementGuid>52b64dd1-7283-40e6-aa8e-915e939048da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>74d77b86-ba0d-463b-ab7e-31cab7a94ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tenants' or . = 'Tenants')]</value>
      <webElementGuid>f4fb70b3-8b48-421d-a1cd-48448322e4b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
